---
- name: create user
  hosts: localhost
  become: true
  become_user: root
  tasks:
    - name: creating ansible user
      user:
        name: Ramanji-devops
        password: Ramanji-devops
        state: present
       
