---
- name: create user
  hosts: all
  become: true
  tasks:
    - name: creating ansible user
      user:
        name: Ramanji-devops
        password: Ramanji-devops
        state: present
       
