---
- name: create user
  hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - name: creating ansible user
      user:
        name: Ramanji-devops
        password: Ramanji-devops
        state: present
       
